import React from "react";
import "../styles/IntroPage.css";

export default function IntroDashboard({ demoData }) {
  const { videos = [], selectedVideos = {}, summaries = {} } = demoData || {};

  const totalVideos = videos.length;
  const selectedCount = Object.values(selectedVideos).filter(Boolean).length;

  return (
    <div className="intro-dashboard-container">
      <div className="dashboard-header">
        <h2 className="dashboard-title">Demo Dashboard</h2>
        <p className="dashboard-description">
          Get AI-generated summaries with topics and rankings.
        </p>
        <div className="stats-container">
          <div className="stat-item">
            <span className="stat-label">Total Videos:</span>
            <span className="stat-value">{totalVideos}</span>
          </div>
          <div className="stat-item">
            <span className="stat-label">Selected Videos:</span>
            <span className="stat-value">{selectedCount}</span>
          </div>
        </div>
      </div>

      <div className="summaries-section">
        <h2 className="section-title">Video Summaries</h2>
        <p className="section-description">
          Below are example summaries generated by our AI. In the full application, these summaries would be created based on the content of the videos you select.
        </p>

        {Object.entries(summaries).map(([videoId, data]) => {
          const video = videos.find(v => v.videoId === videoId);
          if (!video) return null;

          return (
            <div key={videoId} className="summary-card">
              <div className="summary-header">
                <h3 className="video-title">
                  <i className="fas fa-video"></i>
                  {video.title}
                </h3>
                <p className="channel-name">
                  <i className="fas fa-user-circle"></i>
                  {video.channelTitle}
                </p>
              </div>

              <div className="summary-content">
                <h4 className="summary-subtitle">
                  <i className="fas fa-file-alt"></i>
                  Summary
                </h4>
                <p className="summary-text">{data.summary}</p>

                <h4 className="summary-subtitle">
                  <i className="fas fa-tags"></i>
                  Topics
                </h4>
                <div className="topics-container">
                  {data.topics.map((topic, index) => (
                    <span key={index} className="topic-tag">
                      {topic}
                    </span>
                  ))}
                </div>
              </div>

              <div className="summary-actions">
                <button className="save-button" >
                  <i className="fas fa-save"></i>
                  Save Summary
                </button>
              </div>
            </div>
          );
        })}
      </div>


      <button className="continue-button" >
        <i className="fas fa-history"></i>
        View History
      </button>
    </div>
  );
} 